# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'C:\Users\user\Desktop\PYQT\converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import requests
import xml.etree.ElementTree as ET


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(248, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAmount = QtWidgets.QLabel(Form)
        self.labelAmount.setObjectName("labelAmount")
        self.verticalLayout.addWidget(self.labelAmount)
        self.lineEditAmount = QtWidgets.QLineEdit(Form)
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.verticalLayout.addWidget(self.lineEditAmount)
        self.comboBoxCurrency = QtWidgets.QComboBox(Form)
        self.comboBoxCurrency.setObjectName("comboBoxCurrency")
        self.comboBoxCurrency.addItem("")
        self.comboBoxCurrency.addItem("")
        self.comboBoxCurrency.addItem("")
        self.comboBoxCurrency.addItem("")
        self.comboBoxCurrency.addItem("")
        self.verticalLayout.addWidget(self.comboBoxCurrency)
        self.labelResult = QtWidgets.QPushButton(Form)
        self.labelResult.setObjectName("labelResult")
        self.verticalLayout.addWidget(self.labelResult)
        self.labelResult_2 = QtWidgets.QLabel(Form)
        self.labelResult_2.setObjectName("labelResult_2")
        self.verticalLayout.addWidget(self.labelResult_2)
        self.labelResult_2.raise_()
        self.labelAmount.raise_()
        self.lineEditAmount.raise_()
        self.comboBoxCurrency.raise_()
        self.labelResult.raise_()
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # -------- ДОБАВЛЕННЫЙ КОД --------
        self.rates = {}
        self.load_rates()
        self.labelResult.clicked.connect(self.convert_currency)
        # ---------------------------------

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Конвертер валют в рубли"))
        self.labelAmount.setText(_translate("Form", "Введите сумму:"))
        self.lineEditAmount.setPlaceholderText(_translate("Form", "Введите число"))
        self.comboBoxCurrency.setItemText(0, _translate("Form", "USD (Доллар)"))
        self.comboBoxCurrency.setItemText(1, _translate("Form", "EUR (Евро)"))
        self.comboBoxCurrency.setItemText(2, _translate("Form", "JPY (Иена)"))
        self.comboBoxCurrency.setItemText(3, _translate("Form", "CNY (Юань)"))
        self.comboBoxCurrency.setItemText(4, _translate("Form", "GBP (Фунт стерлингов)"))
        self.labelResult.setText(_translate("Form", "Рассчитать"))
        self.labelResult_2.setText(_translate("Form", "Результат:"))

    # -------- ДОБАВЛЕННЫЕ ФУНКЦИИ --------

    def load_rates(self):
        try:
            url = "https://www.cbr.ru/scripts/XML_daily.asp"
            response = requests.get(url)
            root = ET.fromstring(response.content)

            for valute in root.findall("Valute"):
                char_code = valute.find("CharCode").text
                value = float(valute.find("Value").text.replace(",", "."))
                nominal = int(valute.find("Nominal").text)
                self.rates[char_code] = value / nominal

        except Exception as e:
            self.labelResult_2.setText("Ошибка загрузки курсов")

    def convert_currency(self):
        try:
            amount = float(self.lineEditAmount.text().replace(",", "."))
            currency_text = self.comboBoxCurrency.currentText()
            currency_code = currency_text.split()[0]

            if currency_code in self.rates:
                rate = self.rates[currency_code]
                result = amount * rate
                self.labelResult_2.setText(f"Результат: {result:.2f} RUB")
            else:
                self.labelResult_2.setText("Курс не найден")

        except ValueError:
            self.labelResult_2.setText("Введите корректное число")

    # -------------------------------------


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())